import Foundation

extension CGFloat {
    static var one: CGFloat { return 1 }
    static var fractional1_3: CGFloat { 1/3 }
    static var point0: CGFloat { return 0 }
    static var point0_8: CGFloat { return 0.08 }
    static var point0_16: CGFloat { return 0.16 }
    static var point0_18: CGFloat { return 0.18 }
    static var point0_25: CGFloat { return 0.25 }
    static var point0_2: CGFloat { return 0.2 }
    static var point0_3: CGFloat { return 0.3 }
    static var point0_34: CGFloat { return 0.34 }
    static var point0_4: CGFloat { return 0.4 }
    static var point0_5: CGFloat { return 0.5 }
    static var point0_6: CGFloat { return 0.6 }
    static var point0_75: CGFloat { return 0.75 }
    static var point0_9: CGFloat { return 0.9 }
    static var point1: CGFloat { return 1 }
    static var point1_25: CGFloat { return 1.25 }
    static var point2: CGFloat { return 2 }
    static var point2_5: CGFloat { return 2.5 }
    static var point3: CGFloat { return 3 }
    static var point4: CGFloat { return 4 }
    static var point5: CGFloat { return 5 }
    static var point6: CGFloat { return 6 }
    static var point7: CGFloat { return 7 }
    static var point8: CGFloat { return 8 }
    static var point9: CGFloat { return 9 }
    static var point10: CGFloat { return 10 }
    static var point11: CGFloat { return 11 }
    static var point12: CGFloat { return 12 }
    static var point13: CGFloat { return 13 }
    static var point14: CGFloat { return 14 }
    static var point15: CGFloat { return 15 }
    static var point16: CGFloat { return 16 }
    static var point17: CGFloat { return 17 }
    static var point18: CGFloat { return 18 }
    static var point19: CGFloat { return 19 }
    static var point20: CGFloat { return 20 }
    static var point21: CGFloat { return 21 }
    static var point22: CGFloat { return 22 }
    static var point23: CGFloat { return 23 }
    static var point24: CGFloat { return 24 }
    static var point25: CGFloat { return 25 }
    static var point26: CGFloat { return 26 }
    static var point27: CGFloat { return 27 }
    static var point28: CGFloat { return 28 }
    static var point29: CGFloat { return 29 }
    static var point30: CGFloat { return 30 }
    static var point32: CGFloat { return 32 }
    static var point34: CGFloat { return 34 }
    static var point36: CGFloat { return 36 }
    static var point40: CGFloat { return 40 }
    static var point43: CGFloat { return 43 }
    static var point44: CGFloat { return 44 }
    static var point45: CGFloat { return 45 }
    static var point47: CGFloat { return 47 }
    static var point48: CGFloat { return 48 }
    static var point49: CGFloat { return 49 }
    static var point50: CGFloat { return 50 }
    static var point52: CGFloat { return 52 }
    static var point53: CGFloat { return 53 }
    static var point54: CGFloat { return 54 }
    static var point55: CGFloat { return 55 }
    static var point56: CGFloat { return 56 }
    static var point58: CGFloat { return 58 }
    static var point60: CGFloat { return 60 }
    static var point62: CGFloat { return 62 }
    static var point63: CGFloat { return 63 }
    static var point70: CGFloat { return 70 }
    static var point72: CGFloat { return 72 }
    static var point76: CGFloat { return 76 }
    static var point78: CGFloat { return 78 }
    static var point79: CGFloat { return 79 }
    static var point80: CGFloat { return 80 }
    static var point86: CGFloat { return 86 }
    static var point87: CGFloat { return 87 }
    static var point90: CGFloat { return 90 }
    static var point95: CGFloat { return 95 }
    static var point96: CGFloat { return 96 }
    static var point100: CGFloat { return 100 }
    static var point102: CGFloat { return 102 }
    static var point103: CGFloat { return 103 }
    static var point114: CGFloat { return 114 }
    static var point120: CGFloat { return 120 }
    static var point125: CGFloat { return 125 }
    static var point127: CGFloat { return 127 }
    static var point132: CGFloat { return 132 }
    static var point135: CGFloat { return 135 }
    static var point136: CGFloat { return 136 }
    static var point139: CGFloat { return 139 }
    static var point140: CGFloat { return 140 }
    static var point142: CGFloat { return 142 }
    static var point143: CGFloat { return 143 }
    static var point147: CGFloat { return 147 }
    static var point150: CGFloat { return 150 }
    static var point155: CGFloat { return 155 }
    static var point156: CGFloat { return 156 }
    static var point160: CGFloat { return 160 }
    static var point163: CGFloat { return 163 }
    static var point170: CGFloat { return 170 }
    static var point180: CGFloat { return 180 }
    static var point187: CGFloat { return 187 }
    static var point192: CGFloat { return 192 }
    static var point200: CGFloat { return 200 }
    static var point205: CGFloat { return 205 }
    static var point230: CGFloat { return 230 }
    static var point235: CGFloat { return 235 }
    static var point250: CGFloat { return 250 }
    static var point260: CGFloat { return 260 }
    static var point265: CGFloat { return 265 }
    static var point290: CGFloat { return 290 }
    static var point294: CGFloat { return 294 }
    static var point295: CGFloat { return 295 }
    static var point314: CGFloat { return 314 }
    static var point323: CGFloat { return 323 }
    static var point334: CGFloat { return 334 }
    static var point350: CGFloat { return 350 }
    static var point360: CGFloat { return 360 }
    static var point400: CGFloat { return 400 }
    static var point430: CGFloat { return 430 }
    static var point450: CGFloat { return 450 }
    static var point484: CGFloat { return 484 }
    static var point533: CGFloat { return 533 }
    static var point750: CGFloat { return 750 }
    static var point1200: CGFloat { return 1200 }
}


